version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sky_db
      SPRING_DATASOURCE_USERNAME: sky_user
      SPRING_DATASOURCE_PASSWORD: sky_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    depends_on:
      - db

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sky_user
      POSTGRES_PASSWORD: sky_pass
      POSTGRES_DB: sky_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:v2.21.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-rules.yml:/etc/prometheus/prometheus-rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

volumes:
  postgres-data: