global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'prometheus-rules.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ '127.0.0.1:9090' ]
  - job_name: 'SkyUser'
    basic_auth:
      username: 'admin@example.com'
      password: 'admin'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ '127.0.0.1:8080' ]
