groups:
  - name: custom_rules
    rules:
      - record: heap_memory_usage_percentage
        expr: (sum by (instance)(jvm_memory_used_bytes{area="heap"}) / sum by (instance)(jvm_memory_max_bytes{area="heap"})) * 100